FLAGS = -Wall -g

all: question1 question2 question3 question4 question5 question6

clean:
	rm -f question1 question2 question3 question4 question5 question6 question2.output

question1: question1.c
	gcc -o question1 question1.c $(FLAGS)

question2: question2.c
	gcc -o question2 question2.c $(FLAGS)

question3: question3.c
	gcc -o question3 question3.c $(FLAGS)

question4: question4.c
	gcc -o question4 question4.c $(FLAGS)

question5: question5.c
	gcc -o question5 question5.c $(FLAGS)

question6: question6.c
	gcc -o question6 question6.c $(FLAGS)
